In [1]:
import pandas as pd

In [2]:
df= pd.read_csv("/kaggle/input/datasets/rohankashyap5526/quots-data/qoute_dataset.csv")

In [3]:
q1=df['quote']

In [4]:
q1[0]

'“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”'

In [5]:
q1[0][0]

'“'

In [6]:
q2=q1.apply(lambda x: x.replace(q1[0][0], "").replace(q1[0][-1], ""))

In [7]:
q2[0]

'The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.'

In [8]:
q3= q2.apply(lambda x: x.split())

In [9]:
q3

0       [The, world, as, we, have, created, it, is, a,...
1       [It, is, our, choices,, Harry,, that, show, wh...
2       [There, are, only, two, ways, to, live, your, ...
3       [The, person,, be, it, gentleman, or, lady,, w...
4       [Imperfection, is, beauty,, madness, is, geniu...
                              ...                        
3033    [The, past, beats, inside, me, like, a, second...
3034    [Damn,, Claire., Warn, a, guy, before, you, do...
3035    [Can, you, be, a, girl, for, a, few, seconds?"...
3036    [That's, what, fiction, is, for., It's, for, g...
3037    [If, we, have, no, peace,, it, is, because, we...
Name: quote, Length: 3038, dtype: object

In [10]:
input=[]
for i in q3:
    # print(i)
    for j in range(1, len(i)):
        input.append(i[:j])
        
    # break

In [11]:
# input

In [12]:
input_string=[]
for seq in input:
    word= " ".join(seq)
    input_string.append(word)

In [13]:
# input_string

In [14]:
len(input_string)

85432

In [15]:
output= []
for i in range(len(input_string)):
    word=  input_string[i].split()
    # print(word[-1])
    output.append(word[-1])
    # break
    

In [16]:
output[:10]

['The', 'world', 'as', 'we', 'have', 'created', 'it', 'is', 'a', 'process']

In [17]:
input_string[:10]

['The',
 'The world',
 'The world as',
 'The world as we',
 'The world as we have',
 'The world as we have created',
 'The world as we have created it',
 'The world as we have created it is',
 'The world as we have created it is a',
 'The world as we have created it is a process']

In [18]:
output.pop(0)

'The'

In [19]:
input_string.pop()

'If we have no peace, it is because we have forgotten that we belong to each'

In [20]:
output[:10]

['world', 'as', 'we', 'have', 'created', 'it', 'is', 'a', 'process', 'of']

In [21]:
input_string[:10]

['The',
 'The world',
 'The world as',
 'The world as we',
 'The world as we have',
 'The world as we have created',
 'The world as we have created it',
 'The world as we have created it is',
 'The world as we have created it is a',
 'The world as we have created it is a process']

In [22]:
len(output)

85431

In [23]:
len(input_string)

85431

In [24]:
from tensorflow.keras.preprocessing.text import Tokenizer


2026-04-15 06:44:31.299270: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1776235471.517063      55 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1776235471.573113      55 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1776235472.078066      55 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1776235472.078109      55 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1776235472.078113      55 computation_placer.cc:177] computation placer alr

In [25]:
tokenizer=Tokenizer()

In [26]:
tokenizer.fit_on_texts(input_string)

In [28]:
vocab_size=len(tokenizer.word_index)

In [30]:
# tokenizer.word_index

In [31]:
X= input_string
y= output

In [32]:
X_seq= tokenizer.texts_to_sequences(X)
y_seq= tokenizer.texts_to_sequences(y)

In [33]:
X_seq[:10]

[[1],
 [1, 83],
 [1, 83, 14],
 [1, 83, 14, 27],
 [1, 83, 14, 27, 16],
 [1, 83, 14, 27, 16, 815],
 [1, 83, 14, 27, 16, 815, 11],
 [1, 83, 14, 27, 16, 815, 11, 9],
 [1, 83, 14, 27, 16, 815, 11, 9, 5],
 [1, 83, 14, 27, 16, 815, 11, 9, 5, 1989]]

In [34]:
y_seq[:10]

[[83], [14], [27], [16], [815], [11], [9], [5], [1989], [7]]

In [36]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [37]:
max_len=0
for i in X_seq:
    if len(i)>max_len:
        max_len=len(i)

In [38]:
max_len

748

In [39]:
X_pad= pad_sequences(X_seq, maxlen= max_len, padding='pre')

In [40]:
X_pad[:10]

array([[   0,    0,    0, ...,    0,    0,    1],
       [   0,    0,    0, ...,    0,    1,   83],
       [   0,    0,    0, ...,    1,   83,   14],
       ...,
       [   0,    0,    0, ...,  815,   11,    9],
       [   0,    0,    0, ...,   11,    9,    5],
       [   0,    0,    0, ...,    9,    5, 1989]], dtype=int32)

In [42]:
y_seq[:10]

[[83], [14], [27], [16], [815], [11], [9], [5], [1989], [7]]

In [43]:
import numpy as np

In [45]:
# np.array(y_seq)

In [51]:
out=[]
for i in y_seq:
    # print(i)
    if len(i)>0:
        out.append(i[0])
    else:
        out.append(0)
    

In [52]:
out[:10]

[83, 14, 27, 16, 815, 11, 9, 5, 1989, 7]

In [53]:
len(out)

85431

In [54]:
len(X_pad)

85431

In [55]:
y_out= np.array(out)

In [56]:
y_out[:10]

array([  83,   14,   27,   16,  815,   11,    9,    5, 1989,    7])

In [58]:
from tensorflow.keras.utils import to_categorical

In [60]:

y_cat= to_categorical(y_out, num_classes=vocab_size+1 )

In [61]:
y_cat[:10]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [62]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, LSTM, GRU



In [63]:
emd_dim= 50
rnn_units= 64

In [64]:
max_len

748

In [65]:
model= Sequential(
    [
        Embedding(input_dim= vocab_size+1, output_dim= emd_dim, input_length= max_len),
        LSTM(rnn_units),
        Dense(vocab_size+1, activation='softmax')
    ]
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(
I0000 00:00:1776236981.563884      55 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 13757 MB memory:  -> device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5
I0000 00:00:1776236981.570384      55 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 13757 MB memory:  -> device: 1, name: Tesla T4, pci bus id: 0000:00:05.0, compute capability: 7.5


In [66]:
model.compile(loss='categorical_crossentropy', optimizer="adam", metrics=['accuracy'])

In [67]:
model.fit(X_pad, y_cat, epochs=5, verbose=1)

Epoch 1/5


I0000 00:00:1776237107.769528    1143 cuda_dnn.cc:529] Loaded cuDNN version 91002


2670/2670 ━━━━━━━━━━━━━━━━━━━━ 69s 24ms/step - accuracy: 0.0400 - loss: 6.7692
Epoch 2/5
2670/2670 ━━━━━━━━━━━━━━━━━━━━ 65s 24ms/step - accuracy: 0.0733 - loss: 6.0539
Epoch 3/5
2670/2670 ━━━━━━━━━━━━━━━━━━━━ 65s 25ms/step - accuracy: 0.1002 - loss: 5.7311
Epoch 4/5
2670/2670 ━━━━━━━━━━━━━━━━━━━━ 65s 24ms/step - accuracy: 0.1169 - loss: 5.4673
Epoch 5/5
2670/2670 ━━━━━━━━━━━━━━━━━━━━ 65s 24ms/step - accuracy: 0.1339 - loss: 5.2491


In [78]:
text="There are only"


seq= tokenizer.texts_to_sequences([text])



In [79]:
seq

[[49, 12, 76]]

In [80]:
seq= pad_sequences(seq, maxlen=max_len, padding='pre')

In [81]:
seq

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 

In [82]:
pred=model.predict(seq)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step


In [83]:
pred

array([[3.0624974e-03, 3.8915806e-02, 1.0595050e-02, ..., 3.0824503e-06,
        7.4561058e-06, 1.3068674e-07]], dtype=float32)

In [84]:
word=np.argmax(pred)

In [85]:
tokenizer.index_word[word]

'the'

In [87]:
text="Try not to"



for i in range(5):
    seq= tokenizer.texts_to_sequences([text])
    seq= pad_sequences(seq, maxlen=max_len, padding='pre')
    pred=model.predict(seq, verbose=0)
    word=np.argmax(pred)
    word= tokenizer.index_word[word]
    text+= " "+ word

text

'Try not to be a book to be'

In [88]:
model.save('next_word.h5')

In [90]:
import joblib 
joblib.dump(tokenizer,'tkn.joblib')

['tkn.joblib']